server:
  port: ${PORT:8080}
  servlet:
    context-path: /admission-event-service/api
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 32KB
    use-forward-headers: true

admission-event-service:
  oauthserver: ${OAUTH_HOST:http://ecampus2-trimix.uesiglo21.edu.ar:8080}
  version: ${ADMISSION_EVENT_SERVICE_VERSION:1.0}
  
admission-api-service:
  base-url: ${ADMISSION_API_URL:http://apidev.ues21.edu.ar/admission-api/api/}

ngg-batch-jobs:
  base-url: ${NGG_BATCH_JOBS_BASE_URL:http://apidev.ues21.edu.ar/ngg-batch-jobs/api/}

oauth.retrofit.oauthUrl: ${OAUTH_URL:http://ecampus2-trimix.uesiglo21.edu.ar:8080/menu/api/oauth2/}
oauth.retrofit.clientid: ${SERVICES_OAUTH_CLIENT_ID:desa}
oauth.retrofit.clientsecret: ${SERVICES_OAUTH_CLIENT_SECRET:desa}

security:
  oauth2:
    client:
      clientId: ${OAUTH_CLIENT_ID:desa}
      clientSecret: ${OAUTH_CLIENT_SECRET:desa}
    resource:
      tokenInfoUri: ${admission-event-service.oauthserver}/menu/api/oauth2/token_info

kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:9092}
  config:
    path: ${ADMISSION_EVENT_KAFKA_CONFIG_PATH:/run/secrets/mensajeria-admision-event-service-confluent-kafka.properties}
  topic:
    admission:
      pre_enrollment: ${PRE_ENROLLMENT_QUEUE:admission.preenrollment}
    academic_life:
      student-record: ${STUDENT_RECORD_QUEUE:academic-life.student-record}
    user:
      contact: ${USER_CONTACT_QUEUE:user.contact}
    assessment:
      report: ${ASSESSMENT_REPORT_QUEUE:assessment.report}
      subscriptGroup: ${ASSESSMENT_SUBSCRIPTGROUP_QUEUE:assessment.group-subscription}

resend:
  file-location: ${RESEND_FILE_LOCATION:./resend}

# ALL, ERROR, NOTHING
callback:
  send-level: ${CALLBACK_LEVEL:ALL}